run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - revive

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true
    disable:
      - shadow

  revive:
    rules:
      - name: exported
        disabled: false

  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - unparam

    # Ignore long lines in tests
    - path: _test\.go
      linters:
        - lll

  max-same-issues: 0
  max-issues-per-linter: 0

output:
  sort-results: true
